name: 🐛 Bug Report
description: Report a problem with Headerizer
title: "[BUG] "
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What happened?
  - type: textarea
    attributes:
      label: Steps to Reproduce
